version: '3.8'

services:
  # Jupyter Lab para análises exploratórias
  jupyter:
    image: jupyter/datascience-notebook:latest
    container_name: ecommerce-jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work/notebooks
      - ./data:/home/jovyan/work/data
      - ./sql:/home/jovyan/work/sql
      - ./python:/home/jovyan/work/python
      - ./keys:/home/jovyan/work/keys:ro
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - GRANT_SUDO=yes
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - GCP_DATASET_ID=${GCP_DATASET_ID}
      - GOOGLE_APPLICATION_CREDENTIALS=/home/jovyan/work/keys/gcp-key.json
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''
    networks:
      - ecommerce-network

  # Container Python para ETL e scripts
  python-etl:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce-python
    volumes:
      - ./data:/app/data
      - ./python:/app/python
      - ./sql:/app/sql
      - ./keys:/app/keys:ro
    environment:
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - GCP_DATASET_ID=${GCP_DATASET_ID}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/keys/gcp-key.json
      - PYTHONUNBUFFERED=1
    stdin_open: true
    tty: true
    networks:
      - ecommerce-network
    depends_on:
      - postgres

  # PostgreSQL local para testes (opcional)
  postgres:
    image: postgres:15-alpine
    container_name: ecommerce-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=olist_ecommerce
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./sql/01_schema:/docker-entrypoint-initdb.d
    networks:
      - ecommerce-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # PgAdmin para interface gráfica (opcional)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ecommerce-pgadmin
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - ecommerce-network
    depends_on:
      - postgres

volumes:
  postgres-data:
  pgadmin-data:

networks:
  ecommerce-network:
    driver: bridge